site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/carla
docs_dir: Docs

pages:
- Home: 'index.md'
- Using CARLA:
  - 'How to run CARLA server and client': 'how_to_run.md'
  - 'CARLA Settings': 'carla_settings.md'
  - 'Measurements': 'measurements.md'
  - 'Cameras and sensors': 'cameras_and_sensors.md'
  - 'CARLA without Display and Selecting GPUs': 'carla_headless.md'
  - 'Benchmark': 'benchmark.md'
  - 'F.A.Q.': 'faq.md'
- Building from source:
  - 'How to build on Linux': 'how_to_build_on_linux.md'
  - 'How to build on Windows': 'how_to_build_on_windows.md'
  - 'How to add Automotive Materials': 'how_to_add_automotive_materials.md'
- Contributing:
  - 'Contribution guidelines': 'CONTRIBUTING.md'
  - 'Coding standard': 'coding_standard.md'
  - 'Code of conduct': 'CODE_OF_CONDUCT.md'
- Development:
  - 'Map customization': 'map_customization.md'
  - 'How to add assets': 'how_to_add_assets.md'
  - 'CARLA design': 'carla_design.md'
  - 'CarlaServer documentation': 'carla_server.md'

markdown_extensions:
  - admonition
