carla:
  # the network connection for the python connection to CARLA
  host: localhost
  port: 2000
  # the vehicle that acts as ego vehicle for this ros bridge instance
  ego_vehicle_role_name: hero
